name             'cookbooks/3nel'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cookbooks/3nel'
long_description 'Installs/Configures cookbooks/3nel'
version          '0.1.0'
