name             '3nel'
maintainer       'Serge Hovsepian'
maintainer_email 'hserge@gmail.com'
license          'All rights reserved'
description      'Installs/Configures cookbooks/3nel'
long_description 'Installs/Configures cookbooks/3nel'
version          '0.1.0'
